services:
  - type: web
    name: aidocumentcompanion-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
